server:
  port: 8888

carofjzc:
  brand: BWO
  price: 100000
spring:
  #数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ors?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 15879305710
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid配置
    druid:
      aop-patterns: com.example.demo.*
      filters: stat, wall
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
      filter:
        stat:
          slow-sql-millis: 1000  #超过1000毫秒算慢查询
      max-active: 12 #最大活跃数
  #mybatis等相关配置
  jdbc:
    template:
      query-timeout: 3  #3秒没查到就算超时
  mybatis:
    #mapper配置文件
    #config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml

    #type-aliases-package: com.example.demo.mapper

